[project]
name = "websotester"
version = "0.1.0"
description = "Local web UI for testing WebSocket servers (ws:// and wss://)"
readme = "README.md"
authors = [
    { name = "Denis Leroy", email = "denis@soundhound.com" }
]
requires-python = ">=3.14"
dependencies = [
    "starlette>=1.7.0",
    "uvicorn[standard]>=0.53.0",
    "websockets>=17.1",
]

[project.scripts]
websotester = "websotester:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
